title: "Danilo Croce"
name: "Danilo Croce"
description: "Associate Professor in Computer Science · NLP · LLMs · IR · HRI · Multimodality"
url: "https://crux82.github.io"
baseurl: "" 

theme: minimal-mistakes-jekyll
remote_theme: "mmistakes/minimal-mistakes@4.24.0"

minimal_mistakes_skin: "mint"   # colore accento

plugins:
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

paginate: 10
locale: "en-US"

author:
  name   : "Danilo Croce"
  avatar : "/assets/images/avatar.jpg"
  bio    : "Associate Professor at University of Rome Tor Vergata. Research in NLP, Large Language Models, Multimodality, Human-Robot Interaction."
  links:
    - label: "Google Scholar"
      icon: "fas fa-graduation-cap"
      url: "https://scholar.google.it/citations?user=dXewdYAAAAAJ"
    - label: "Scopus"
      icon: "fas fa-university"
      url: "https://www.scopus.com/authid/detail.uri?authorId=27567467600"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/crux82"
    - label: "Twitter"
      icon: "fab fa-twitter"
      url: "https://twitter.com/yourhandle"

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true